name: Create Release Package

on:
  push:
    tags:
      - 'v*'  # Run workflow on version tags

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Archive
        run: git archive --format=zip --output=release.zip HEAD

      - name: Upload Release Archive
        uses: actions/upload-artifact@v3
        with:
          name: release-archive
          path: release.zip

      - name: Publish Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
